### ISSUE TITLE
Support for .net 4.7 or 4.8

### ISSUE THREAD

**Issue by ponvignesh** [ConnerPhillis/FluentLicensing#1]
Hi, am not able to compile on 4.7 or 4.8.
There is not support for 
Rsa.ExportRSAPublicKey & rsa.ImportRSAPublicKey. in .net 4.7 & 4.8 .
Can you point me in the right direction to solve this 
Thanks

**Comment by ConnerPhillis** [comment]
Hey @ponvignesh, thanks for using the library!

Unfortunately, the library targets .NET Standard 2.1, and Microsoft won't be upgrading Framework to implement the new APIs [anytime soon](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/). I've looked in to custom importing / exporting the public and private key, but to be honest with you it looks like a serious pain.

I'm willing to do this work, but first I want to give you another option. [.NET 5 is projected to release at .NET Conf 2020 on the 10th](https://visualstudiomagazine.com/articles/2020/10/13/net-5-rc2.aspx). It should include every library that you're using or planning on using in 4.7 & 4.8, and will include the missing cryptography methods. If your use case prohibits this, feel free to let me know and I'll further evaluate backing up the targeted .NET Standard version.

As a final personal opinion, I think you'd be best served by using this as an opportunity to upgrade your stack. Microsoft has only been providing security updates for Framework for a while now, and, again just my opinion, the longer you wait the more libraries you'll find that are targeting versions of .NET newer than 4.7 & 4.8. I'm not familiar with your use case, so I don't know if something would be prohibiting you or not, just thought that might help 😃 

Again, thanks for using the library!

**Comment by ponvignesh** [comment]
hi, 
thanks for the reply..  and a wonderful library.. 
Ya you are right. but there is some existing work with older .NET frameworks, which will be a pain to upgrade. but eventually we must upgrade one way or another.. :-)
but any way , i really appreciate your work..   Thanks.  👍
